### ISSUE TITLE
CAD/SCAD source?

### ISSUE THREAD

**Issue by manutenfruits** [aderusha/DDD-Printable-Wall-Control-System#3]
Thanks for this library! Would it be possible for you to share the CAD files you might have used to create the tools? I want to create my own centerpieces but have to recreate everything.

**Comment by aderusha** [comment]
That's a reasonable request but it requires a shameful admission: I've been using SketchUp for ~15 years at this point and while it's poorly suited for 3D printing... It's what I know how to use.

So good news: YES I CAN provide the CAD files for everything.  Bad news: it's all being done in SketchUp (lol).  Further complicating things is that I'm working in SU2021, which has changed the document format such that tools like F360 can no longer import them.

**Comment by manutenfruits** [comment]
That's fine, you built an awesome library! I'll gladly take SketchUp files and learn the basics, I just want to tweak some tool holders and take measurements to recreate on SolidWorks.

Thanks!

**Comment by rkaronde** [comment]
I created a few tool holders in Fusion 360 after measuring the STL for the dimensions of other tool holder and where the slots/notches should be, and they fit great with the existing hooks.

Having said that if you can export and share STEP files that would be awesome..

**Comment by aderusha** [comment]
Annoyingly, STEP export isn't offered by SketchUp without expensive 3rd-party add-ons.  STL is the most-portable solution I have available to me at the moment.

Someday I'll stop being dumb and learn F360...

Anyway I don't think I made it clear in my initial reply, the SU2021 source files can be found in the repo here: https://github.com/aderusha/DDD-Printable-Wall-Control-System/tree/main/SketchUp%20Sources

**Comment by aderusha** [comment]
Oh and one more thing that might be surprising if you open this project up in SU2021 - everything is 1000x bigger than it is IRL.  

Among the many reasons nobody should use SU for 3D printing is the extremely poor handling of small dimensions.  The solution I use is to model everything at 1000:1 scale, which is pretty easy as 1mm becomes 1m.  When you export to STL, select "meters" as the unit and everything should work out OK.

**Comment by manutenfruits** [comment]
Thanks for the quick response and the files.
