### ISSUE TITLE
Enter these designs in the latest PrusaPrinters contest

### ISSUE THREAD

**Issue by rkaronde** [aderusha/DDD-Printable-Wall-Control-System#4]
The latest contest at PrusaPrinters.org is about organization, and this project will be a great fit.

Please submit it.

[PrusaPrinters 3D Contest:
Organization Tools](https://www.prusaprinters.org/contest/41492)

**Comment by aderusha** [comment]
Good idea, [done](https://www.prusaprinters.org/prints/52618-ddd-printable-wall-control-system)!
