### ISSUE TITLE
My newly purchased 5,5mm Flat Driver no longer fits in this: Centerpieces/Tool_hooks/2x5 Wera Kraftform Plus 160i-6.stl

### ISSUE THREAD

**Issue by snebes** [aderusha/DDD-Printable-Wall-Control-System#56]
This was a set purchased in 2022 from Amazon US. Specifically, this set:

https://products.wera.de/en/tools_for_electricians_kraftform_plus__series_100_vde_160_i_6_rack.html

The 5.5mm flat driver no longer fits in the supplied location on this STL: Centerpieces/Tool_hooks/2x5 Wera Kraftform Plus 160i-6.stl 

All other drivers fit exactly as expected.

I'm not able to find any dimensional specifications for that specific driver, but I measured this with my caliper:

shaft near top: 8.9mm
handle base (hexagon edge-to-edge): 23.0mm (a hair under)

**Comment by aderusha** [comment]
Looking to either close or resolve this issue - the model as provided fits the measurements you indicate, which also match the driver. 

Here's a look at that model, the hex cutout is 23.4mm dia and the shaft cutout is 9mm dia: https://i.imgur.com/4UqmA5k.png

On the off chance that you're still watching this, go ahead and respond if this is still an issue and I'll re-open.  Sorry for the late response!
