### ISSUE TITLE
Model error on Dowel Rod Holder

### ISSUE THREAD

**Issue by bgautrea** [aderusha/DDD-Printable-Wall-Control-System#6]
The 2x4 3-4in Dowel Rod Hangers show a problem on the hook in Ultimaker Cura and ultimately dont print the hook. Not sure if this can be fixed in the slicer or if there's something up with the model. I may be doing something wrong here but the U-Brackets printed with no problem.

https://github.com/aderusha/DDD-Printable-Wall-Control-System/blob/main/Sidepieces/Dowel_rod_hanger/2x4%203-4in%20Dowel%20Rod%20Hanger%20Right.stl

![image](https://user-images.githubusercontent.com/15523167/106813504-b1ab6900-6636-11eb-8f49-33615b09f239.png)

**Comment by aderusha** [comment]
It looks like Cura has some problem with the small radius on that part.  Maybe try PrusaSlicer? https://i.imgur.com/2Px77hI.png

The part is for sure manifold, so the issue here is the slicer.

**Comment by bgautrea** [comment]
Thanks!. PrusaSlicer is working though I think it's still odd that some of the models work in Cura while others have the manifold issue. I assume the radius is == in all the models where the hook meets the rest of the model.
