### ISSUE TITLE
Unable to download any angle bracket sidepieces.

### ISSUE THREAD

**Issue by MrJSaul** [aderusha/DDD-Printable-Wall-Control-System#60]
Unable to download any angle bracket sidepieces.  There is no button for downloading on any of the pages in this section it seems.  Am I missing something?  All the other items have had a "Download" button and had no issue.

**Comment by rgeyer** [comment]
You should also be able to click on the `Raw` button which will open it up in your browser. Then use the file menu or right click on the page and "Save As.." to save the file.

**Comment by ffcruz85** [comment]
what @rgeyer said, or just clone the whole repository locally. If you don't want to mess with git or installing github desktop, you can just go to the main page of the repo, click the green code button, and then click download ZIP to get the whole repo downloaded. If you clone it, however, you can more easily get updates to it.
![image](https://user-images.githubusercontent.com/2352828/220507807-4207ee0d-29d3-4bba-9257-eb6a173e11cb.png)

**Comment by MrJSaul** [comment]
Thanks @rgeyer @ffcruz85.  I really appreciate you both taking the time to point this noob in the right direction and educating me on what is possible.

**Comment by ffcruz85** [comment]
No problem. Even if you're not familiar with git, you could try the GitHub desktop app, it's fairly user friendly and then you can "sync" (pull commits to local clone of the repository) and have the new stuff that gets added here. Maybe even contribute your own designs 😉

**Comment by MrJSaul** [comment]
@ffcruz85 
I did remix 2 items for this system.  How can I add them? 
1) Open top small mason jar holder (remix: https://www.thingiverse.com/thing:2552603)
2) Benzomatic propane bottle/torch holder (remix https://www.thingiverse.com/thing:3332178)

**Comment by ffcruz85** [comment]
So, you have to do it on your own copy of the repository, and then ask to merge it back into this main one. You don't need to install the app and call do it all on the website.

1. First, you need to fork the repo, which is getting your own copy of the repo that you then own and can edit. Just go to the main page and click fork on the buttons at the top. Then you will have your own copy at https://github.com/MrJSaul/DDD-Printable-Wall-Control-System
2. Then add the files for those things you made under the centerpieces/tool_hooks folder
3. Preferably, name your files according to the pattern used, which is explained in the README.md file in that tool_hooks folder, e.g.: 2x4_Propane_Torch_Holder.stl
4. You should also edit the README.md file to add your tools to the list so people can find them, it's formatted in markdown, which is a syntax for making text formatting in plain text, making the links to the files, etc. Easiest way: just copy one of the existing tool holder descriptions and change the name, description, and link to the file.
5. Now that you are done adding your files and describing them in the readme in your own repo, just come back here to @aderusha 's main repo, and click on pull requests, create new pull request, and it should already have your fork in the options of where you are pulling from. Just write a quick note saying what you are adding, click submit, and that's it. @aderusha will see it, and if it's all good, he'll merge and then you tools will be available here for the community!

You can just go to pull requests page right now, and click on closed to see those that have already been merged - you will see one i recently added to do exactly what you did, and it will show the changes I made, which you can use as an example

**Comment by ffcruz85** [comment]
@MrJSaul also, if you are no longer having the original problem for which you opened this issue, you can go ahead and close it. That concludes this very short course on contributing in github :)

**Comment by ffcruz85** [comment]
@MrJSaul PS.: If you have any CAD type files or a STEP file for your designs, it might also be nice to include those so people can make further remixes!
