### ISSUE TITLE
Honeycomb Centerpiece is backwards

### ISSUE THREAD

**Issue by bmatheny** [aderusha/DDD-Printable-Wall-Control-System#90]
The honeycomb centerpieces from [here](https://github.com/aderusha/DDD-Printable-Wall-Control-System/tree/main/Centerpieces/Honeycomb_Storage_Wall) are (I think) backwards.

You can see from [the printables image](https://media.printables.com/media/prints/152592/rich_content/fedc425d-c796-4abe-bbe3-388cdf62ad12/thumbs/inside/1920x1440/png/x9rztdw14gsa1.webp) that the "thicker part faces you". The way the centerpieces were designed, the thicker part faces away from you. So the only way to use the flat side pieces has the honeycomb wall facing away from you. If you try to use the centerpiece with the thick part facing towards you, it doesn't fit with a flat side piece.

The drawings are in sketch up, otherwise I'd put up a PR for it.

**Comment by aderusha** [comment]
Great catch, and fixed.  Thanks!
